name: Shoe Application CI/CD Pipeline

on: 
  push: 
    branches:
      - main

jobs:
  build-and-deploy-application:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build Application
        run: npm run build

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Authenticate using the Firebase CI token
        run: firebase deploy --only hosting --debug --token "${{ secrets.FIREBASE_TOKEN }}"
